version: '3'

services:
  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: sleep infinity
    volumes:
      - .:/app
  redis:
    container_name: redis
    image: redislabs/rebloom:2.2.4
