version: '3'

services:
  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: sleep infinity
    volumes:
      - .:/app
  redis:
    container_name: redis
    build:
      dockerfile: Dockerfile.redis
      context: .
